// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDvMsUCbVWPukBCskBdG23YtqFgtJrjFOQ',
    appId: '1:29580934456:web:16c58f4fe1b3b20f0c55cd',
    messagingSenderId: '29580934456',
    projectId: 'smartservices-aacff',
    authDomain: 'smartservices-aacff.firebaseapp.com',
    storageBucket: 'smartservices-aacff.firebasestorage.app',
    measurementId: 'G-98MG5PH87F',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDh4TkGRfJVWm79LZaooUhkEmk6KxuWtmQ',
    appId: '1:29580934456:android:60c0bb08ac6569520c55cd',
    messagingSenderId: '29580934456',
    projectId: 'smartservices-aacff',
    storageBucket: 'smartservices-aacff.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA19C5JkyW1vFNChcnfV3EIl8Ons93iqXI',
    appId: '1:29580934456:ios:a6b9ad267db4a7b30c55cd',
    messagingSenderId: '29580934456',
    projectId: 'smartservices-aacff',
    storageBucket: 'smartservices-aacff.firebasestorage.app',
    androidClientId: '29580934456-1bf7b7eau9l166e5rh6an64ri7cna3jk.apps.googleusercontent.com',
    iosClientId: '29580934456-rsrg5jjqdilqdrs5cb61hldjea90mucq.apps.googleusercontent.com',
    iosBundleId: 'com.example.smartAdmin',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA19C5JkyW1vFNChcnfV3EIl8Ons93iqXI',
    appId: '1:29580934456:ios:a6b9ad267db4a7b30c55cd',
    messagingSenderId: '29580934456',
    projectId: 'smartservices-aacff',
    storageBucket: 'smartservices-aacff.firebasestorage.app',
    androidClientId: '29580934456-1bf7b7eau9l166e5rh6an64ri7cna3jk.apps.googleusercontent.com',
    iosClientId: '29580934456-rsrg5jjqdilqdrs5cb61hldjea90mucq.apps.googleusercontent.com',
    iosBundleId: 'com.example.smartAdmin',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDvMsUCbVWPukBCskBdG23YtqFgtJrjFOQ',
    appId: '1:29580934456:web:7d168ef7fcbe421d0c55cd',
    messagingSenderId: '29580934456',
    projectId: 'smartservices-aacff',
    authDomain: 'smartservices-aacff.firebaseapp.com',
    storageBucket: 'smartservices-aacff.firebasestorage.app',
    measurementId: 'G-VT635RK1V1',
  );
}
